const language ={
    EN:{
        'Antwerpen': 'Antwerpen',
        'Brabant - VV': 'Brabant - VV',
        'Current': 'Current',
        'Club Friendlies 5':'Club Friendlies 5',
        'Final Group Stage': 'Final Group Stage',
        'Group Stage': 'Group Stage',
        'Group 13': 'Group 13',
        'Highland League': 'Highland League',
        'Isthmian': 'Isthmian',
        'Limburg': 'Limburg',
        'Luxembourg': 'Luxembourg', 
        'Lowland League': 'Lowland League',
        'Namur': 'Namur',
        'Northern': 'Northern',
        'Regular Season': 'Regular Season',
        'Nord / Nordost': 'Nord / Nordost',
        'Süd / Südwest': 'Süd / Südwest',
        'North': 'North',
        'Oost-Vlaanderen': 'Oost-Vlaanderen',
        'South': 'South',
        'West': 'West',
        '1st Phase': '1st Phase',
        '3rd Place Final':'3rd Place Final',
        '5th Round': '5th Round', 
        'VV A': 'VV A',  
        'VV B': 'VV B',
        'Apertura': 'Apertura',
        'Clausura': 'Clausura',
        null : 'Friendlies',
      },
    ES:{
      'Antwerpen': 'Antwerpen',
      'Brabant - VV': 'Brabante - VV',
      'Current': 'Actual',
      'Club Friendlies 5': 'Amistoso',
      'Final Group Stage': 'Fase Final de grupos',
      'Group Stage': 'Fase de Grupos',
      'Group 13': 'Grupo 13',
      'Luxembourg': 'Luxemburgo', 
      'Highland League': 'Liga Tierras Altas',
       'Isthmian': 'Istmico',
      'Limburg': 'Limburgo',
      'Lowland League': 'Liga Tierras bajas',
      'Namur': 'Namur',
      'Northern': 'Norteña',
      'Regular Season': 'Regular',
      'Nord / Nordost': 'Norte / Noreste',
      'Süd / Südwest': 'Sur / Suroeste',
      'North': 'Norte',
      'Oost-Vlaanderen': 'Flandes Oriental',
      'South': 'Sur',
      'West': 'Oeste',
      '1st Phase': '1ra Fase',
      '3rd Place Final':'Final tercer lugar',
      '5th Round': '5ta Ronda', 
       'VV A': 'VV A',  
       'VV B': 'VV B',
      'Apertura': 'Apertura',
      'Clausura': 'Clausura',
       null : 'Amistoso',
    },
}

const translateText = (text,lang) => {
    return language[lang][text]; 
}

export default translateText;